apiVersion: v1
kind: Service
metadata:
  annotations:
    # TODO: Check whether AWS/Azure can use internal load balancers. Google
    # can't, unfortunately.
    # service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    # service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    # cloud.google.com/load-balancer-type: "Internal"
    networking.gke.io/load-balancer-type: 'Internal'
    # NOTE: new in k8s 1.16, so currently must be manually applied to the load balancer
    networking.gke.io/internal-load-balancer-allow-global-access: 'true'
  labels:
    k8s-app: kube-dns
  name: kube-dns-lb
  namespace: kube-system
spec:
  ports:
  - name: dns
    port: 53
    protocol: UDP
    targetPort: 53
  selector:
    k8s-app: kube-dns
  sessionAffinity: None
  type: LoadBalancer
